# Change these first
owner: woodruffandtheschnibbleofazimuth
repo: Le-Alternative-Status

# Add your sites here
sites:
  - name: Le Alternative
    url: https://www.lealternative.net
    icon: https://www.lealternative.net/wp-content/uploads/2020/05/cropped-logowhite-blu-favicon2-32x32.png
  - name: Privacy Test
    url: https://privacytest.lealternative.net
    icon: https://www.lealternative.net/wp-content/uploads/2021/03/logowhite-blu-test.png
  - name: Bot Telegram
    url: $SECRET_SITE
    icon: https://www.lealternative.net/wp-content/uploads/2021/03/logowhite-bot.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /Le-Alternative-Status
  logoUrl: https://www.lealternative.net/wp-content/uploads/2020/05/cropped-logowhite-blu.png
  name: Le Alternative | Status
  introTitle: "**Le Alternative**, ecco lo stato dei nostri servizi"
  introMessage: Questo servizio funziona attraverso le GitHub Actions. Quando un servizio non funziona viene aperta in automatico una *issue* su [GitHub](https://github.com/woodruffandtheschnibbleofazimuth/Le-Alternative-Status)
  navbar:
    - title: Status
      href: /Le-Alternative-Status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://www.lealternative.net
    - title: Gruppo **Telegram**
      href: https://t.me/LeAlternativeGruppoUfficiale

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
